version: "3"

networks:
  dbnet:
    driver: bridge

services:
  pgserver:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: weatherwise-pgserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5433
    networks:
      - dbnet
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped

  # APP*****************************************
  springbootapp:
    image: springbootapp:latest
    build:
      context: .
    container_name: springbootapp
    expose:
      - 8082
    ports:
      - 8082:8080
    restart: unless-stopped
    depends_on:
      - pgserver
    networks:
      - dbnet
    command: /bin/bash

volumes:
  postgres-data:
